# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Venvy < Formula
  desc "A fast modular (see modules/) sh hook system bound to subcomamnds. Useful for bootstrapping and managing local development and CI environments."
  homepage ""
  version "0.2.0"
  license "MIT"
  bottle :unneeded

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/cloudsynth/venvy/releases/download/v0.2.0/venvy_0.2.0_Darwin_x86_64.tar.gz"
      sha256 "982c20314dfab75cf81933657fdd217302a3667c087000398f3637bb8afb4d66"
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      url "https://github.com/cloudsynth/venvy/releases/download/v0.2.0/venvy_0.2.0_Linux_x86_64.tar.gz"
      sha256 "ca4698feb417a2e18647eb5e53e2730509b5b9c89583b23f1192cd9f873d77eb"
    end
  end

  def install
    bin.install "venvy"
  end
end
